enum Operator {
  IN = 'IN',
  NOT_IN = 'NOT IN',
  EMPTY = 'EMPTY',
  NOT_EMPTY = 'NOT EMPTY',
  EQUALS = '=',
  LOWER_OR_EQUAL_THAN = '<=',
  IN_CHILDREN_LIST = 'IN CHILDREN',
  NOT_IN_CHILDREN_LIST = 'NOT IN CHILDREN',
  UNCLASSIFIED = 'UNCLASSIFIED',
  CLASSIFIED = 'CLASSIFIED',
}

export {Operator};
