const BaseSelect = require('pim/form/common/fields/select');
const {formatTimezoneOffsetFromUTC} = require('pim/user/tools/timezone-formatter');

class TimezoneField extends BaseSelect {
  /**
   * {@inheritdoc}
   */
  configure() {
    BaseSelect.prototype.configure.apply(this, arguments);
    this.config.choices = {
      Africa: {
        'Africa/Abidjan': 'Abidjan GMT',
        'Africa/Accra': 'Accra GMT',
        'Africa/Addis_Ababa': 'Addis Ababa EAT',
        'Africa/Algiers': 'Algiers CET',
        'Africa/Asmara': 'Asmara EAT',
        'Africa/Bamako': 'Bamako GMT',
        'Africa/Bangui': 'Bangui WAT',
        'Africa/Banjul': 'Banjul GMT',
        'Africa/Bissau': 'Bissau GMT',
        'Africa/Blantyre': 'Blantyre CAT',
        'Africa/Brazzaville': 'Brazzaville WAT',
        'Africa/Bujumbura': 'Bujumbura CAT',
        'Africa/Cairo': 'Cairo EET',
        'Africa/Casablanca': 'Casablanca WEST',
        'Africa/Ceuta': 'Ceuta CEST',
        'Africa/Conakry': 'Conakry GMT',
        'Africa/Dakar': 'Dakar GMT',
        'Africa/Dar_es_Salaam': 'Dar es Salaam EAT',
        'Africa/Djibouti': 'Djibouti EAT',
        'Africa/Douala': 'Douala WAT',
        'Africa/El_Aaiun': 'El Aaiun WEST',
        'Africa/Freetown': 'Freetown GMT',
        'Africa/Gaborone': 'Gaborone CAT',
        'Africa/Harare': 'Harare CAT',
        'Africa/Johannesburg': 'Johannesburg SAST',
        'Africa/Juba': 'Juba EAT',
        'Africa/Kampala': 'Kampala EAT',
        'Africa/Khartoum': 'Khartoum EAT',
        'Africa/Kigali': 'Kigali CAT',
        'Africa/Kinshasa': 'Kinshasa WAT',
        'Africa/Lagos': 'Lagos WAT',
        'Africa/Libreville': 'Libreville WAT',
        'Africa/Lome': 'Lome GMT',
        'Africa/Luanda': 'Luanda WAT',
        'Africa/Lubumbashi': 'Lubumbashi CAT',
        'Africa/Lusaka': 'Lusaka CAT',
        'Africa/Malabo': 'Malabo WAT',
        'Africa/Maputo': 'Maputo CAT',
        'Africa/Maseru': 'Maseru SAST',
        'Africa/Mbabane': 'Mbabane SAST',
        'Africa/Mogadishu': 'Mogadishu EAT',
        'Africa/Monrovia': 'Monrovia GMT',
        'Africa/Nairobi': 'Nairobi EAT',
        'Africa/Ndjamena': 'Ndjamena WAT',
        'Africa/Niamey': 'Niamey WAT',
        'Africa/Nouakchott': 'Nouakchott GMT',
        'Africa/Ouagadougou': 'Ouagadougou GMT',
        'Africa/Porto-Novo': 'Porto-Novo WAT',
        'Africa/Sao_Tome': 'Sao Tome GMT',
        'Africa/Tripoli': 'Tripoli EET',
        'Africa/Tunis': 'Tunis CET',
        'Africa/Windhoek': 'Windhoek WAT',
      },
      America: {
        'America/Adak': 'Adak HDT',
        'America/Anchorage': 'Anchorage AKDT',
        'America/Anguilla': 'Anguilla AST',
        'America/Antigua': 'Antigua AST',
        'America/Araguaina': 'Araguaina BRT',
        'America/Argentina/Buenos_Aires': 'Argentina - Buenos Aires ART',
        'America/Argentina/Catamarca': 'Argentina - Catamarca ART',
        'America/Argentina/Cordoba': 'Argentina - Cordoba ART',
        'America/Argentina/Jujuy': 'Argentina - Jujuy ART',
        'America/Argentina/La_Rioja': 'Argentina - La Rioja ART',
        'America/Argentina/Mendoza': 'Argentina - Mendoza ART',
        'America/Argentina/Rio_Gallegos': 'Argentina - Rio Gallegos ART',
        'America/Argentina/Salta': 'Argentina - Salta ART',
        'America/Argentina/San_Juan': 'Argentina - San Juan ART',
        'America/Argentina/San_Luis': 'Argentina - San Luis ART',
        'America/Argentina/Tucuman': 'Argentina - Tucuman ART',
        'America/Argentina/Ushuaia': 'Argentina - Ushuaia ART',
        'America/Aruba': 'Aruba AST',
        'America/Asuncion': 'Asuncion PYT',
        'America/Atikokan': 'Atikokan EST',
        'America/Bahia': 'Bahia BRT',
        'America/Bahia_Banderas': 'Bahia Banderas CDT',
        'America/Barbados': 'Barbados AST',
        'America/Belem': 'Belem BRT',
        'America/Belize': 'Belize CST',
        'America/Blanc-Sablon': 'Blanc-Sablon AST',
        'America/Boa_Vista': 'Boa Vista AMT',
        'America/Bogota': 'Bogota COT',
        'America/Boise': 'Boise MDT',
        'America/Cambridge_Bay': 'Cambridge Bay MDT',
        'America/Campo_Grande': 'Campo Grande AMT',
        'America/Cancun': 'Cancun EST',
        'America/Caracas': 'Caracas VET',
        'America/Cayenne': 'Cayenne GFT',
        'America/Cayman': 'Cayman EST',
        'America/Chicago': 'Chicago CDT',
        'America/Chihuahua': 'Chihuahua MDT',
        'America/Costa_Rica': 'Costa Rica CST',
        'America/Creston': 'Creston MST',
        'America/Cuiaba': 'Cuiaba AMT',
        'America/Curacao': 'Curacao AST',
        'America/Danmarkshavn': 'Danmarkshavn GMT',
        'America/Dawson': 'Dawson PDT',
        'America/Dawson_Creek': 'Dawson Creek MST',
        'America/Denver': 'Denver MDT',
        'America/Detroit': 'Detroit EDT',
        'America/Dominica': 'Dominica AST',
        'America/Edmonton': 'Edmonton MDT',
        'America/Eirunepe': 'Eirunepe ACT',
        'America/El_Salvador': 'El Salvador CST',
        'America/Fort_Nelson': 'Fort Nelson MST',
        'America/Fortaleza': 'Fortaleza BRT',
        'America/Glace_Bay': 'Glace Bay ADT',
        'America/Godthab': 'Godthab WGST',
        'America/Goose_Bay': 'Goose Bay ADT',
        'America/Grand_Turk': 'Grand Turk AST',
        'America/Grenada': 'Grenada AST',
        'America/Guadeloupe': 'Guadeloupe AST',
        'America/Guatemala': 'Guatemala CST',
        'America/Guayaquil': 'Guayaquil ECT',
        'America/Guyana': 'Guyana GYT',
        'America/Halifax': 'Halifax ADT',
        'America/Havana': 'Havana CDT',
        'America/Hermosillo': 'Hermosillo MST',
        'America/Indiana/Indianapolis': 'Indiana - Indianapolis EDT',
        'America/Indiana/Knox': 'Indiana - Knox CDT',
        'America/Indiana/Marengo': 'Indiana - Marengo EDT',
        'America/Indiana/Petersburg': 'Indiana - Petersburg EDT',
        'America/Indiana/Tell_City': 'Indiana - Tell City CDT',
        'America/Indiana/Vevay': 'Indiana - Vevay EDT',
        'America/Indiana/Vincennes': 'Indiana - Vincennes EDT',
        'America/Indiana/Winamac': 'Indiana - Winamac EDT',
        'America/Inuvik': 'Inuvik MDT',
        'America/Iqaluit': 'Iqaluit EDT',
        'America/Jamaica': 'Jamaica EST',
        'America/Juneau': 'Juneau AKDT',
        'America/Kentucky/Louisville': 'Kentucky - Louisville EDT',
        'America/Kentucky/Monticello': 'Kentucky - Monticello EDT',
        'America/Kralendijk': 'Kralendijk AST',
        'America/La_Paz': 'La Paz BOT',
        'America/Lima': 'Lima PET',
        'America/Los_Angeles': 'Los Angeles PDT',
        'America/Lower_Princes': 'Lower Princes AST',
        'America/Maceio': 'Maceio BRT',
        'America/Managua': 'Managua CST',
        'America/Manaus': 'Manaus AMT',
        'America/Marigot': 'Marigot AST',
        'America/Martinique': 'Martinique AST',
        'America/Matamoros': 'Matamoros CDT',
        'America/Mazatlan': 'Mazatlan MDT',
        'America/Menominee': 'Menominee CDT',
        'America/Merida': 'Merida CDT',
        'America/Metlakatla': 'Metlakatla AKDT',
        'America/Mexico_City': 'Mexico City CDT',
        'America/Miquelon': 'Miquelon PMDT',
        'America/Moncton': 'Moncton ADT',
        'America/Monterrey': 'Monterrey CDT',
        'America/Montevideo': 'Montevideo UYT',
        'America/Montserrat': 'Montserrat AST',
        'America/Nassau': 'Nassau EDT',
        'America/New_York': 'New York EDT',
        'America/Nipigon': 'Nipigon EDT',
        'America/Nome': 'Nome AKDT',
        'America/Noronha': 'Noronha FNT',
        'America/North_Dakota/Beulah': 'North Dakota - Beulah CDT',
        'America/North_Dakota/Center': 'North Dakota - Center CDT',
        'America/North_Dakota/New_Salem': 'North Dakota - New Salem CDT',
        'America/Ojinaga': 'Ojinaga MDT',
        'America/Panama': 'Panama EST',
        'America/Pangnirtung': 'Pangnirtung EDT',
        'America/Paramaribo': 'Paramaribo SRT',
        'America/Phoenix': 'Phoenix MST',
        'America/Port-au-Prince': 'Port-au-Prince EST',
        'America/Port_of_Spain': 'Port of Spain AST',
        'America/Porto_Velho': 'Porto Velho AMT',
        'America/Puerto_Rico': 'Puerto Rico AST',
        'America/Rainy_River': 'Rainy River CDT',
        'America/Rankin_Inlet': 'Rankin Inlet CDT',
        'America/Recife': 'Recife BRT',
        'America/Regina': 'Regina CST',
        'America/Resolute': 'Resolute CDT',
        'America/Rio_Branco': 'Rio Branco ACT',
        'America/Santarem': 'Santarem BRT',
        'America/Santiago': 'Santiago CLT',
        'America/Santo_Domingo': 'Santo Domingo AST',
        'America/Sao_Paulo': 'Sao Paulo BRT',
        'America/Scoresbysund': 'Scoresbysund EGST',
        'America/Sitka': 'Sitka AKDT',
        'America/St_Barthelemy': 'St Barthelemy AST',
        'America/St_Johns': 'St Johns NDT',
        'America/St_Kitts': 'St Kitts AST',
        'America/St_Lucia': 'St Lucia AST',
        'America/St_Thomas': 'St Thomas AST',
        'America/St_Vincent': 'St Vincent AST',
        'America/Swift_Current': 'Swift Current CST',
        'America/Tegucigalpa': 'Tegucigalpa CST',
        'America/Thule': 'Thule ADT',
        'America/Thunder_Bay': 'Thunder Bay EDT',
        'America/Tijuana': 'Tijuana PDT',
        'America/Toronto': 'Toronto EDT',
        'America/Tortola': 'Tortola AST',
        'America/Vancouver': 'Vancouver PDT',
        'America/Whitehorse': 'Whitehorse PDT',
        'America/Winnipeg': 'Winnipeg CDT',
        'America/Yakutat': 'Yakutat AKDT',
        'America/Yellowknife': 'Yellowknife MDT',
      },
      Antarctica: {
        'Antarctica/Casey': 'Casey AWST',
        'Antarctica/Davis': 'Davis DAVT',
        'Antarctica/DumontDUrville': 'DumontDUrville DDUT',
        'Antarctica/Macquarie': 'Macquarie MIST',
        'Antarctica/Mawson': 'Mawson MAWT',
        'Antarctica/McMurdo': 'McMurdo NZST',
        'Antarctica/Palmer': 'Palmer CLT',
        'Antarctica/Rothera': 'Rothera ROTT',
        'Antarctica/Syowa': 'Syowa SYOT',
        'Antarctica/Troll': 'Troll CEST',
        'Antarctica/Vostok': 'Vostok VOST',
      },
      Arctic: {
        'Arctic/Longyearbyen': 'Longyearbyen CEST',
      },
      Asia: {
        'Asia/Aden': 'Aden AST',
        'Asia/Almaty': 'Almaty +06',
        'Asia/Amman': 'Amman EEST',
        'Asia/Anadyr': 'Anadyr ANAT',
        'Asia/Aqtau': 'Aqtau +05',
        'Asia/Aqtobe': 'Aqtobe +05',
        'Asia/Ashgabat': 'Ashgabat TMT',
        'Asia/Baghdad': 'Baghdad AST',
        'Asia/Bahrain': 'Bahrain AST',
        'Asia/Baku': 'Baku AZT',
        'Asia/Bangkok': 'Bangkok ICT',
        'Asia/Barnaul': 'Barnaul +07',
        'Asia/Beirut': 'Beirut EEST',
        'Asia/Bishkek': 'Bishkek KGT',
        'Asia/Brunei': 'Brunei BNT',
        'Asia/Chita': 'Chita YAKT',
        'Asia/Choibalsan': 'Choibalsan CHOST',
        'Asia/Colombo': 'Colombo IST',
        'Asia/Damascus': 'Damascus EEST',
        'Asia/Dhaka': 'Dhaka BDT',
        'Asia/Dili': 'Dili TLT',
        'Asia/Dubai': 'Dubai GST',
        'Asia/Dushanbe': 'Dushanbe TJT',
        'Asia/Gaza': 'Gaza EEST',
        'Asia/Hebron': 'Hebron EEST',
        'Asia/Ho_Chi_Minh': 'Ho Chi Minh ICT',
        'Asia/Hong_Kong': 'Hong Kong HKT',
        'Asia/Hovd': 'Hovd HOVST',
        'Asia/Irkutsk': 'Irkutsk IRKT',
        'Asia/Jakarta': 'Jakarta WIB',
        'Asia/Jayapura': 'Jayapura WIT',
        'Asia/Jerusalem': 'Jerusalem IDT',
        'Asia/Kabul': 'Kabul AFT',
        'Asia/Kamchatka': 'Kamchatka PETT',
        'Asia/Karachi': 'Karachi PKT',
        'Asia/Kathmandu': 'Kathmandu NPT',
        'Asia/Khandyga': 'Khandyga YAKT',
        'Asia/Kolkata': 'Kolkata IST',
        'Asia/Krasnoyarsk': 'Krasnoyarsk KRAT',
        'Asia/Kuala_Lumpur': 'Kuala Lumpur MYT',
        'Asia/Kuching': 'Kuching MYT',
        'Asia/Kuwait': 'Kuwait AST',
        'Asia/Macau': 'Macau CST',
        'Asia/Magadan': 'Magadan MAGT',
        'Asia/Makassar': 'Makassar WITA',
        'Asia/Manila': 'Manila PHT',
        'Asia/Muscat': 'Muscat GST',
        'Asia/Nicosia': 'Nicosia EEST',
        'Asia/Novokuznetsk': 'Novokuznetsk KRAT',
        'Asia/Novosibirsk': 'Novosibirsk NOVT',
        'Asia/Omsk': 'Omsk OMST',
        'Asia/Oral': 'Oral +05',
        'Asia/Phnom_Penh': 'Phnom Penh ICT',
        'Asia/Pontianak': 'Pontianak WIB',
        'Asia/Pyongyang': 'Pyongyang KST',
        'Asia/Qatar': 'Qatar AST',
        'Asia/Qyzylorda': 'Qyzylorda +06',
        'Asia/Rangoon': 'Rangoon MMT',
        'Asia/Riyadh': 'Riyadh AST',
        'Asia/Sakhalin': 'Sakhalin SAKT',
        'Asia/Samarkand': 'Samarkand UZT',
        'Asia/Seoul': 'Seoul KST',
        'Asia/Shanghai': 'Shanghai CST',
        'Asia/Singapore': 'Singapore SGT',
        'Asia/Srednekolymsk': 'Srednekolymsk SRET',
        'Asia/Taipei': 'Taipei CST',
        'Asia/Tashkent': 'Tashkent UZT',
        'Asia/Tbilisi': 'Tbilisi GET',
        'Asia/Tehran': 'Tehran IRDT',
        'Asia/Thimphu': 'Thimphu BTT',
        'Asia/Tokyo': 'Tokyo JST',
        'Asia/Tomsk': 'Tomsk +07',
        'Asia/Ulaanbaatar': 'Ulaanbaatar ULAST',
        'Asia/Urumqi': 'Urumqi XJT',
        'Asia/Ust-Nera': 'Ust-Nera VLAT',
        'Asia/Vientiane': 'Vientiane ICT',
        'Asia/Vladivostok': 'Vladivostok VLAT',
        'Asia/Yakutsk': 'Yakutsk YAKT',
        'Asia/Yekaterinburg': 'Yekaterinburg YEKT',
        'Asia/Yerevan': 'Yerevan AMT',
      },
      Atlantic: {
        'Atlantic/Azores': 'Azores AZOST',
        'Atlantic/Bermuda': 'Bermuda ADT',
        'Atlantic/Canary': 'Canary WEST',
        'Atlantic/Cape_Verde': 'Cape Verde CVT',
        'Atlantic/Faroe': 'Faroe WEST',
        'Atlantic/Madeira': 'Madeira WEST',
        'Atlantic/Reykjavik': 'Reykjavik GMT',
        'Atlantic/South_Georgia': 'South Georgia GST',
        'Atlantic/St_Helena': 'St Helena GMT',
        'Atlantic/Stanley': 'Stanley FKST',
      },
      Australia: {
        'Australia/Adelaide': 'Adelaide ACST',
        'Australia/Brisbane': 'Brisbane AEST',
        'Australia/Broken_Hill': 'Broken Hill ACST',
        'Australia/Currie': 'Currie AEST',
        'Australia/Darwin': 'Darwin ACST',
        'Australia/Eucla': 'Eucla ACWST',
        'Australia/Hobart': 'Hobart AEST',
        'Australia/Lindeman': 'Lindeman AEST',
        'Australia/Lord_Howe': 'Lord Howe LHST',
        'Australia/Melbourne': 'Melbourne AEST',
        'Australia/Perth': 'Perth AWST',
        'Australia/Sydney': 'Sydney AEST',
      },
      Europe: {
        'Europe/Amsterdam': 'Amsterdam CEST',
        'Europe/Andorra': 'Andorra CEST',
        'Europe/Astrakhan': 'Astrakhan +04',
        'Europe/Athens': 'Athens EEST',
        'Europe/Belgrade': 'Belgrade CEST',
        'Europe/Berlin': 'Berlin CEST',
        'Europe/Bratislava': 'Bratislava CEST',
        'Europe/Brussels': 'Brussels CEST',
        'Europe/Bucharest': 'Bucharest EEST',
        'Europe/Budapest': 'Budapest CEST',
        'Europe/Busingen': 'Busingen CEST',
        'Europe/Chisinau': 'Chisinau EEST',
        'Europe/Copenhagen': 'Copenhagen CEST',
        'Europe/Dublin': 'Dublin IST',
        'Europe/Gibraltar': 'Gibraltar CEST',
        'Europe/Guernsey': 'Guernsey BST',
        'Europe/Helsinki': 'Helsinki EEST',
        'Europe/Isle_of_Man': 'Isle of Man BST',
        'Europe/Istanbul': 'Istanbul EEST',
        'Europe/Jersey': 'Jersey BST',
        'Europe/Kaliningrad': 'Kaliningrad EET',
        'Europe/Kiev': 'Kiev EEST',
        'Europe/Kirov': 'Kirov +03',
        'Europe/Lisbon': 'Lisbon WEST',
        'Europe/Ljubljana': 'Ljubljana CEST',
        'Europe/London': 'London BST',
        'Europe/Luxembourg': 'Luxembourg CEST',
        'Europe/Madrid': 'Madrid CEST',
        'Europe/Malta': 'Malta CEST',
        'Europe/Mariehamn': 'Mariehamn EEST',
        'Europe/Minsk': 'Minsk MSK',
        'Europe/Monaco': 'Monaco CEST',
        'Europe/Moscow': 'Moscow MSK',
        'Europe/Oslo': 'Oslo CEST',
        'Europe/Paris': 'Paris CEST',
        'Europe/Podgorica': 'Podgorica CEST',
        'Europe/Prague': 'Prague CEST',
        'Europe/Riga': 'Riga EEST',
        'Europe/Rome': 'Rome CEST',
        'Europe/Samara': 'Samara SAMT',
        'Europe/San_Marino': 'San Marino CEST',
        'Europe/Sarajevo': 'Sarajevo CEST',
        'Europe/Simferopol': 'Simferopol MSK',
        'Europe/Skopje': 'Skopje CEST',
        'Europe/Sofia': 'Sofia EEST',
        'Europe/Stockholm': 'Stockholm CEST',
        'Europe/Tallinn': 'Tallinn EEST',
        'Europe/Tirane': 'Tirane CEST',
        'Europe/Ulyanovsk': 'Ulyanovsk +04',
        'Europe/Uzhgorod': 'Uzhgorod EEST',
        'Europe/Vaduz': 'Vaduz CEST',
        'Europe/Vatican': 'Vatican CEST',
        'Europe/Vienna': 'Vienna CEST',
        'Europe/Vilnius': 'Vilnius EEST',
        'Europe/Volgograd': 'Volgograd MSK',
        'Europe/Warsaw': 'Warsaw CEST',
        'Europe/Zagreb': 'Zagreb CEST',
        'Europe/Zaporozhye': 'Zaporozhye EEST',
        'Europe/Zurich': 'Zurich CEST',
      },
      Indian: {
        'Indian/Antananarivo': 'Antananarivo EAT',
        'Indian/Chagos': 'Chagos IOT',
        'Indian/Christmas': 'Christmas CXT',
        'Indian/Cocos': 'Cocos CCT',
        'Indian/Comoro': 'Comoro EAT',
        'Indian/Kerguelen': 'Kerguelen TFT',
        'Indian/Mahe': 'Mahe SCT',
        'Indian/Maldives': 'Maldives MVT',
        'Indian/Mauritius': 'Mauritius MUT',
        'Indian/Mayotte': 'Mayotte EAT',
        'Indian/Reunion': 'Reunion RET',
      },
      Pacific: {
        'Pacific/Apia': 'Apia WSST',
        'Pacific/Auckland': 'Auckland NZST',
        'Pacific/Bougainville': 'Bougainville BST',
        'Pacific/Chatham': 'Chatham CHAST',
        'Pacific/Chuuk': 'Chuuk CHUT',
        'Pacific/Easter': 'Easter EAST',
        'Pacific/Efate': 'Efate VUT',
        'Pacific/Enderbury': 'Enderbury PHOT',
        'Pacific/Fakaofo': 'Fakaofo TKT',
        'Pacific/Fiji': 'Fiji FJT',
        'Pacific/Funafuti': 'Funafuti TVT',
        'Pacific/Galapagos': 'Galapagos GALT',
        'Pacific/Gambier': 'Gambier GAMT',
        'Pacific/Guadalcanal': 'Guadalcanal SBT',
        'Pacific/Guam': 'Guam ChST',
        'Pacific/Honolulu': 'Honolulu HST',
        'Pacific/Johnston': 'Johnston HST',
        'Pacific/Kiritimati': 'Kiritimati LINT',
        'Pacific/Kosrae': 'Kosrae KOST',
        'Pacific/Kwajalein': 'Kwajalein MHT',
        'Pacific/Majuro': 'Majuro MHT',
        'Pacific/Marquesas': 'Marquesas MART',
        'Pacific/Midway': 'Midway SST',
        'Pacific/Nauru': 'Nauru NRT',
        'Pacific/Niue': 'Niue NUT',
        'Pacific/Norfolk': 'Norfolk NFT',
        'Pacific/Noumea': 'Noumea NCT',
        'Pacific/Pago_Pago': 'Pago Pago SST',
        'Pacific/Palau': 'Palau PWT',
        'Pacific/Pitcairn': 'Pitcairn PST',
        'Pacific/Pohnpei': 'Pohnpei PONT',
        'Pacific/Port_Moresby': 'Port Moresby PGT',
        'Pacific/Rarotonga': 'Rarotonga CKT',
        'Pacific/Saipan': 'Saipan ChST',
        'Pacific/Tahiti': 'Tahiti TAHT',
        'Pacific/Tarawa': 'Tarawa GILT',
        'Pacific/Tongatapu': 'Tongatapu TOT',
        'Pacific/Wake': 'Wake WAKT',
        'Pacific/Wallis': 'Wallis WFT',
      },
      Other: {
        UTC: 'UTC',
      },
    };
  }

  /**
   * {@inheritdoc}
   */
  formatChoices(areas: {[key: string]: {[key: string]: string}}): {[key: string]: {[key: string]: string}} {
    return Object.keys(areas).reduce(
      (accumulator, area: string) => ({
        ...accumulator,
        [area]: this.formatTimeZones(areas[area]),
      }),
      {}
    );
  }

  formatTimeZones(timeZones: {[key: string]: string}): {[key: string]: string} {
    return Object.keys(timeZones).reduce(
      (accumulator, timeZone: string) => ({
        ...accumulator,
        [timeZone]: timeZones[timeZone] + this.getTimezoneContext(timeZone),
      }),
      {}
    );
  }

  getTimezoneContext(timeZone: string): string {
    return timeZone === 'UTC' ? '' : ' (UTC' + formatTimezoneOffsetFromUTC(timeZone) + ')';
  }
}

export = TimezoneField;
