module.exports = {
  clearMocks: true,
  moduleFileExtensions: ['js', 'ts', 'tsx'],
  moduleDirectories: ['node_modules', 'src'],
  roots: ['<rootDir>'],
  setupFilesAfterEnv: ['@testing-library/jest-dom/extend-expect'],
  testMatch: ['**/?(*.)+(unit).ts?(x)'],
  testPathIgnorePatterns: ['/node_modules/', '/generator/', 'src/componnents/Guidelines/Illustrations/', 'src/componnents/Guidelines/Icons/'],
  transform: {'^.+\\.tsx?$': 'ts-jest', '^.+\\.mdx$': '@storybook/addon-docs/jest-transform-mdx'},
  transformIgnorePatterns: ['/node_modules/'],
  collectCoverage: true,
  collectCoverageFrom: ['src/**/*.ts?(x)'],
  cacheDirectory: '/tmp/jest',
  coveragePathIgnorePatterns: [
      'src/components/Guidelines/Illustrations',
      'src/components/Guidelines/Icons',
      'src/theme',
      'src/storybook',
      'generator',
      'src/components/index.ts',
      'src/components/index.ts',
      'src/components/Guidelines/index.ts',
      'src/all.visual.tsx',
      'src/shared/PreviewGallery'
  ],
  coverageReporters: ['text-summary', 'html'],
  coverageDirectory: 'coverage',
  coverageThreshold: {
    global: {
      statements: 100,
      functions: 100,
      lines: 100,
    },
  },
};
