bucket_location         = "EU"
firestore_project_id    = "akecld-prd-pim-fire-eur-demo"
google_zone             = "europe-west3-b"
portal_tenant_continent = "europe-west3"
region                  = "europe-west3"
region_prefix           = "demo-eur-w-3"
time_zone               = "Europe/Paris"
