bucket_location         = "EU"
firestore_project_id    = "akecld-prd-pim-fire-eur-demo"
region                  = "europe-west1"
region_prefix           = "demo-euw1"
portal_tenant_continent = "europe-west1"
time_zone               = "Europe/Paris"
