bucket_location           = "EU"
firestore_project_id      = "akecld-prd-pim-fire-eur-demo"
region                    = "europe-west3"
region_prefix             = "demo-euw3"
portal_tenant_continent   = "europe-west3"
cloud_scheduler_time_zone = "Europe/Paris"
