bucket_location           = "US"
firestore_project_id      = "akecld-prd-pim-fire-us-demo"
region                    = "us-central1"
region_prefix             = "demo-usc1"
portal_tenant_continent   = "us-central1"
cloud_scheduler_time_zone = "America/Chicago"
