bucket_location         = "US"
firestore_project_id    = "akecld-prd-pim-fire-us-demo"
google_zone             = "us-central1-b"
portal_tenant_continent = "us-central1"
region                  = "us-central1"
region_prefix           = "us-c-1"
time_zone               = "America/Chicago"
