<?php declare(strict_types=1);

namespace Pim\Upgrade\Schema;

use Akeneo\Apps\Application\Command\CreateAppCommand;
use Akeneo\Apps\Application\Command\CreateAppHandler;
use Akeneo\Apps\Domain\Model\ValueObject\FlowType;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

final class Version_4_0_20191031124707_update_from_clients_to_apps
    extends AbstractMigration
    implements ContainerAwareInterface
{
    /** @var ContainerInterface */
    private $container;

    /**
     * {@inheritdoc}
     */
    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    public function up(Schema $schema) : void
    {
        try {
            $this->migrateToApps();
        } catch (\Exception $e) {
            $this->down($schema);
            throw $e;
        }
    }

    public function down(Schema $schema) : void
    {
        $getAppsDataToClean = <<< SQL
        SELECT code, user_id
        FROM akeneo_app
SQL;
        $statement = $this->connection()->executeQuery($getAppsDataToClean);
        $dataToClean = $statement->fetchAll();

        $deleteApps = <<< SQL
        DELETE FROM akeneo_app
        WHERE code IN (:apps)
SQL;
        $this->connection()->executeQuery(
            $deleteApps,
            ['apps' => array_column($dataToClean, 'code')],
            ['apps' => Connection::PARAM_STR_ARRAY]
        );

        $removeGeneratedUsers = <<< SQL
        DELETE FROM oro_user
        WHERE id IN (:users)
SQL;
        $this->connection()->executeQuery(
            $removeGeneratedUsers,
            ['users' => array_column($dataToClean, 'user_id')],
            ['users' => Connection::PARAM_STR_ARRAY]
        );
    }

    private function migrateToApps(): void
    {
        $selectClients = <<< SQL
    SELECT id, label
    FROM pim_api_client;
SQL;
        $clientsStatement = $this->connection()->executeQuery($selectClients);
        $clients = $clientsStatement->fetchAll();

        $this->skipIf(empty($clients), 'No API connection to migrate.');
        $this->write(sprintf('%s API connections found. They will be migrate to App.', count($clients)));

        $clients = $this->generateAppsCode($clients);

        foreach ($clients as $client) {
            $command = new CreateAppCommand(
                $client['code'],
                substr($client['label'], 0, 97),
                FlowType::OTHER
            );

            $this->createAppHandler()->handle($command);

            $clientToDelete = $this->retrieveAutoGeneratedClientId($client['code']);

            $this->updateAppWithOldClient($client['code'], $client['id']);

            $this->deleteAutoGeneratedClient($clientToDelete);
        }

        $count = $this->countCreatedApps();
        $this->write(sprintf('%s Apps created.', $count));
    }

    private function countCreatedApps(): int
    {
        $countAppsQuery = <<< SQL
SELECT count(code)
FROM akeneo_app
SQL;
        $countApps = $this->connection()->executeQuery($countAppsQuery);

        return (int) $countApps->fetchColumn();
    }

    /**
     * The App has been created with an auto generated client.
     *
     * @param string $code
     *
     * @return string
     *
     * @throws \Doctrine\DBAL\DBALException
     */
    private function retrieveAutoGeneratedClientId(string $code)
    {
        $retrieveNewAppClientId = <<< SQL
SELECT client_id
FROM akeneo_app
WHERE code = :code
SQL;
        $retrieveStatement = $this->connection()->executeQuery($retrieveNewAppClientId, ['code' => $code]);

        return $retrieveStatement->fetchColumn();
    }

    /**
     * App has been created with an auto generated client. The App need to be updated with the old client id.
     *
     * @param string $code
     * @param string $clientId
     *
     * @throws \Doctrine\DBAL\DBALException
     */
    private function updateAppWithOldClient(string $code, string $clientId): void
    {
        $updateAppQuery = <<< SQL
UPDATE akeneo_app
SET client_id = :client_id
WHERE code = :code;
SQL;
        $this->connection()->executeQuery(
            $updateAppQuery,
            [
                'code' => $code,
                'client_id' => $clientId,
            ]
        );
    }

    /**
     * Once the App is updated with old client id we remove the auto generated client.
     *
     * @param string $clientId
     *
     * @throws \Doctrine\DBAL\DBALException
     */
    private function deleteAutoGeneratedClient(string $clientId): void
    {
        $deleteClientQuery = <<< SQL
DELETE from pim_api_client WHERE id = :client_id;
SQL;
        $this->connection()->executeQuery($deleteClientQuery, ['client_id' => $clientId]);
    }

    /**
     * Generate the code of the App in terms of the label of the client.
     * If several App have the same code, it auto increments codes.
     *
     * @param array $clients
     *
     * @return array
     */
    private function generateAppsCode(array $clients): array
    {
        array_walk($clients, function (&$client) {
            $client['code'] = $this->slugify($client['label']);
        });

        return $this->makeAppsCodeUnique($clients);
    }

    /**
     * Auto increments Apps code if needed.
     *
     * @param array $clients
     *
     * @return array
     */
    private function makeAppsCodeUnique(array $clients): array
    {
        $codeOccurence = array_count_values(array_column($clients, 'code'));
        foreach ($clients as $index => $client) {
            $code = $client['code'];

            if (1 < $codeOccurence[$code]) {
                $clients[$index]['code'] = sprintf('%s_%s', $code, (string) $codeOccurence[$code]);
                $codeOccurence[$code]--;
            }
        }

        return $clients;
    }

    private function connection(): Connection
    {
        return $this->container->get('database_connection');
    }

    private function createAppHandler(): CreateAppHandler
    {
        return $this->container->get('akeneo_app.application.handler.create_app');
    }

    private function slugify(string $label): string
    {
        $truncated = substr($label, 0, 97);

        return preg_replace('/[^A-Za-z0-9\-]/', '_', $truncated);
    }
}
