<?php

namespace Pim\Bundle\EnrichBundle\Doctrine\Persister;

use Doctrine\ORM\Persisters\Entity\BasicEntityPersister;

/**
 * We have a lot of concurrent INSERT INTO to save the completeness in the database that generate SQL errors because of
 * duplicated keys. To avoid the concurrent INSERT INTO that could generate a duplicated key, we register a Persister
 * to Doctrine to change the SQL query generated by doctrine to replace the INSERT INTO by a REPLACE INTO only for the
 * completeness objects.
 *
 * @jira https://akeneo.atlassian.net/browse/PIM-7757
 *
 * @author    Benoit Jacquemont <benoit.jacquemont@akeneo.com>
 * @copyright 2018 Akeneo SAS (http://www.akeneo.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
class CompletenessPersister extends BasicEntityPersister
{
    /**
     * {@inheritdoc}
     */
    public function getInsertSQL()
    {
        return str_replace('INSERT INTO ', 'REPLACE INTO ', parent::getInsertSQL());
    }
}
