import {ATTRIBUTE_TYPE as BASE_ATTRIBUTE_TYPE, Attribute, AttributeCode} from '@akeneo-pim-community/structure';

export enum ATTRIBUTE_TYPE {
  TEXT = BASE_ATTRIBUTE_TYPE.TEXT,
  SIMPLE_SELECT = BASE_ATTRIBUTE_TYPE.OPTION_SIMPLE_SELECT,
  MULTI_SELECT = BASE_ATTRIBUTE_TYPE.OPTION_MULTI_SELECT,
  REF_ENTITY = BASE_ATTRIBUTE_TYPE.REFERENCE_ENTITY_SIMPLE_SELECT,
}

type AttributeType = ATTRIBUTE_TYPE;

export type {Attribute, AttributeType, AttributeCode};
