bucket_location         = "EU"
firestore_project_id    = "akecld-prd-pim-fire-eur-dev"
region                  = "europe-west3"
region_prefix           = "dev-euw3"
portal_tenant_continent = "europe-west3"
time_zone               = "Europe/Paris"
