region                = "europe-west3"
bucket_location       = "EU"
firestore_project_id  = "akecld-prd-pim-fire-eur-dev"
region_prefix         = "eur-w-3"
google_zone           = "europe-west3-b"
shared_project_id     = "akecld-prd-pim-saas-shared"
