<?php

namespace Context\Page;

use Behat\Mink\Element\NodeElement;
use SensioLabs\Behat\PageObjectExtension\PageObject\Page;

/**
 * Page object for modal dialog generated by BackBone
 *
 * @author    Romain Monceau <romain@akeneo.com>
 * @copyright 2013 Akeneo SAS (http://www.akeneo.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
class ModalDialog extends Page
{
    /**
     * @var array
     */
    protected $elements = array(
        'modal' => array('css' => 'div.modal')
    );

    /**
     * Confirm action on the grid modal window
     */
    public function confirmOnGridModalWindow()
    {
        $this
            ->getElement('modal')
            ->find('css', 'a.ok')
            ->click();
    }

    /**
     * Cancel action on the grid modal window
     */
    public function cancelOnGridModalWindow()
    {
        $this
            ->getElement('modal')
            ->find('css', 'a.close')
            ->click();
    }
}
