<?php

namespace Oro\Bundle\DataGridBundle\Extension\Sorter;

use Oro\Bundle\DataGridBundle\Datagrid\Builder;
use Oro\Bundle\DataGridBundle\Datasource\DatasourceInterface;
use Oro\Bundle\DataGridBundle\Datasource\OrmDatasource;
use Oro\Bundle\DataGridBundle\Extension\AbstractExtension;

class OrmSorterExtension extends AbstractExtension
{
    /**
     * Configuration tree paths
     */
    const COLUMNS_PATH         = '[sorters][columns]';
    const MULTISORT_PATH       = '[sorters][enable_multisort]';
    const DEFAULT_SORTERS_PATH = '[sorters][default]';

    /**
     * Query param
     */
    const SORTERS_ROOT_PARAM = '_sort_by';

    /**
     * Ascending sorting direction
     */
    const DIRECTION_ASC = "ASC";

    /**
     * Descending sorting direction
     */
    const DIRECTION_DESC = "DESC";

    /** @var array */
    protected $applied = array();

    /**
     * {@inheritDoc}
     */
    public function isApplicable(array $config)
    {
        return $this->accessor->getValue($config, Builder::DATASOURCE_TYPE_PATH) == OrmDatasource::TYPE
            && is_array($this->accessor->getValue($config, self::COLUMNS_PATH));
    }

    /**
     * {@inheritDoc}
     */
    public function visitDatasource(array $config, DatasourceInterface $datasource)
    {
        $sorters = $this->accessor->getValue($config, self::COLUMNS_PATH);

        $defaultSorters = $this->accessor->getValue($config, self::DEFAULT_SORTERS_PATH) ? : array();
        $sortBy         = $this->requestParams->get(self::SORTERS_ROOT_PARAM) ? : $defaultSorters;

        foreach ($sortBy as $column => $direction) {
            if ($sorter = $this->accessor->getValue($sorters, "[$column]")) {
                $direction = $this->normalizeDirection($direction);

                $datasource->getQuery()->addSortOrder($sorter, $direction);
                $this->applied[$column] = $direction;
            }
        }
    }

    /**
     * {@inheritDoc}
     */
    public function visitMetadata(array $config, \stdClass $data)
    {
        parent::visitMetadata($config, $data); // TODO: Change the autogenerated stub
    }

    /**
     * Normalize user input
     *
     * @param string $direction
     *
     * @return string
     */
    protected function normalizeDirection($direction)
    {
        switch (true) {
            case in_array($direction, array(self::DIRECTION_ASC, self::DIRECTION_DESC), true):
                break;
            case ($direction === false):
                $direction = self::DIRECTION_DESC;
                break;
            default:
                $direction = self::DIRECTION_ASC;
        }

        return $direction;
    }
}
