/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AssetFamily {
  identifier: boolean;
  labels: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".+".
     */
    [k: string]: string;
  };
  image: {
    filePath: string;
    originalFilename: string;
    size?: number;
    mimeType?: string;
    extension?: string;
  };
  asset_count: number;
  attributes: {
    type: string;
    identifier: string;
    asset_family_identifier: string;
    code: string;
    labels: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` ".+".
       */
      [k: string]: string;
    };
    is_required: boolean;
    order: number;
    value_per_locale: boolean;
    value_per_channel: boolean;
    max_length?: number;
    is_textarea?: boolean;
    is_rich_text_editor?: boolean;
    validation_rule?: string;
    regular_expression?: string;
    max_file_size?: string;
    allowed_extensions?: string[];
    options?: {
      code: string;
      labels: {
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` ".+".
         */
        [k: string]: string;
      };
    }[];
  }[];
  permission: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".+".
     */
    [k: string]: boolean;
  };
  attribute_as_label: string;
  attribute_as_image: string;
}
