/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BackendAssetFamily {
  identifier: string;
  labels?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "\w+".
     */
    [k: string]: string;
  };
  image?: null | {
    filePath: string;
    originalFilename: string;
    size?: number;
    mimeType?: string;
    extension?: string;
    [k: string]: any;
  };
  attribute_as_label?: string;
  attribute_as_image?: string;
  [k: string]: any;
}
