<?php

return [
    'Doctrine\Bundle\DoctrineBundle\DoctrineBundle'                  => ['all' => true],
    'Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle'        => ['all' => true],
    'Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle'  => ['all' => true],
    'Symfony\Bundle\AsseticBundle\AsseticBundle'                     => ['all' => true],
    'Symfony\Bundle\FrameworkBundle\FrameworkBundle'                 => ['all' => true],
    'Symfony\Bundle\MonologBundle\MonologBundle'                     => ['all' => true],
    'Symfony\Bundle\SecurityBundle\SecurityBundle'                   => ['all' => true],
    'Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle'             => ['all' => true],
    'Symfony\Bundle\TwigBundle\TwigBundle'                           => ['all' => true],
    'Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle'          => ['all' => true],
    'Escape\WSSEAuthenticationBundle\EscapeWSSEAuthenticationBundle' => ['all' => true],
    'FOS\JsRoutingBundle\FOSJsRoutingBundle'                         => ['all' => true],
    'FOS\RestBundle\FOSRestBundle'                                   => ['all' => true],
    'JMS\SerializerBundle\JMSSerializerBundle'                       => ['all' => true],
    'Knp\Bundle\MenuBundle\KnpMenuBundle'                            => ['all' => true],
    'Liip\ImagineBundle\LiipImagineBundle'                           => ['all' => true],
    'Oro\Bundle\AsseticBundle\OroAsseticBundle'                      => ['all' => true],
    'Oro\Bundle\ConfigBundle\OroConfigBundle'                        => ['all' => true],
    'Oro\Bundle\DataGridBundle\OroDataGridBundle'                    => ['all' => true],
    'Oro\Bundle\FilterBundle\OroFilterBundle'                        => ['all' => true],
    'Oro\Bundle\SecurityBundle\OroSecurityBundle'                    => ['all' => true],
    'Oro\Bundle\TranslationBundle\OroTranslationBundle'              => ['all' => true],
    'Oro\Bundle\UserBundle\OroUserBundle'                            => ['all' => true],
    'Akeneo\Bundle\ElasticsearchBundle\AkeneoElasticsearchBundle'    => ['all' => true],
    'Akeneo\Bundle\BatchBundle\AkeneoBatchBundle'                    => ['all' => true],
    'Akeneo\Bundle\BatchQueueBundle\AkeneoBatchQueueBundle'          => ['all' => true],
    'Akeneo\Bundle\BufferBundle\AkeneoBufferBundle'                  => ['all' => true],
    'Akeneo\Bundle\FileStorageBundle\AkeneoFileStorageBundle'        => ['all' => true],
    'Akeneo\Bundle\MeasureBundle\AkeneoMeasureBundle'                => ['all' => true],
    'Akeneo\Bundle\StorageUtilsBundle\AkeneoStorageUtilsBundle'      => ['all' => true],
    'Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle'      => ['all' => true],
    'FOS\OAuthServerBundle\FOSOAuthServerBundle'                     => ['all' => true],
    'Oneup\FlysystemBundle\OneupFlysystemBundle'                     => ['all' => true],
    'Pim\Bundle\FilterBundle\PimFilterBundle'                        => ['all' => true],
    'Pim\Bundle\NavigationBundle\PimNavigationBundle'                => ['all' => true],
    'Pim\Bundle\UserBundle\PimUserBundle'                            => ['all' => true],
    'Akeneo\Bundle\ClassificationBundle\AkeneoClassificationBundle'  => ['all' => true],
    'Pim\Bundle\AnalyticsBundle\PimAnalyticsBundle'                  => ['all' => true],
    'Pim\Bundle\ApiBundle\PimApiBundle'                              => ['all' => true],
    'Pim\Bundle\CatalogBundle\PimCatalogBundle'                      => ['all' => true],
    'Pim\Bundle\CommentBundle\PimCommentBundle'                      => ['all' => true],
    'Pim\Bundle\ConnectorBundle\PimConnectorBundle'                  => ['all' => true],
    'Pim\Bundle\DashboardBundle\PimDashboardBundle'                  => ['all' => true],
    'Pim\Bundle\DataGridBundle\PimDataGridBundle'                    => ['all' => true],
    'Pim\Bundle\EnrichBundle\PimEnrichBundle'                        => ['all' => true],
    'Pim\Bundle\ImportExportBundle\PimImportExportBundle'            => ['all' => true],
    'Pim\Bundle\InstallerBundle\PimInstallerBundle'                  => ['all' => true],
    'Pim\Bundle\LocalizationBundle\PimLocalizationBundle'            => ['all' => true],
    'Pim\Bundle\NotificationBundle\PimNotificationBundle'            => ['all' => true],
    'Pim\Bundle\PdfGeneratorBundle\PimPdfGeneratorBundle'            => ['all' => true],
    'Pim\Bundle\ReferenceDataBundle\PimReferenceDataBundle'          => ['all' => true],
    'Pim\Bundle\UIBundle\PimUIBundle'                                => ['all' => true],
    'Pim\Bundle\VersioningBundle\PimVersioningBundle'                => ['all' => true],
    'Acme\Bundle\AppBundle\AcmeAppBundle'                            => ['all' => true],
    'Sensio\Bundle\DistributionBundle\SensioDistributionBundle'      => ['dev' => true, 'test' => true, 'behat' => true],
    'Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle'            => ['dev' => true, 'test' => true, 'behat' => true],
    'Symfony\Bundle\DebugBundle\DebugBundle'                         => ['dev' => true, 'test' => true, 'behat' => true],
    'Symfony\Bundle\WebProfilerBundle\WebProfilerBundle'             => ['dev' => true, 'test' => true, 'behat' => true],
    'Symfony\Bundle\WebServerBundle\WebServerBundle'                 => ['dev' => true, 'test' => true, 'behat' => true],
];
