#!/bin/bash
set -e

if [ ! -f /srv/pim/behat.yml ]; then
    cp /srv/pim/behat.yml.dist /srv/pim/behat.yml
    sed -i "s/127.0.0.1\//httpd-behat\//g" /srv/pim/behat.yml
    sed -i "s/127.0.0.1/selenium/g" /srv/pim/behat.yml
fi


if [ ! -f /srv/pim/app/config/parameters.yml ]; then
    cp /srv/pim/app/config/parameters.yml.dist /srv/pim/app/config/parameters.yml
    sed -i "s/database_host:                        localhost/database_host:                        mysql/g" /srv/pim/app/config/parameters.yml
    sed -i "s/localhost: 9200/elastic:changeme@elasticsearch:9200/g" /srv/pim/app/config/parameters.yml
fi

if [ ! -f /srv/pim/app/config/parameters_test.yml ]; then
    cp /srv/pim/app/config/parameters_test.yml.dist /srv/pim/app/config/parameters_test.yml
    sed -i "s/database_host:                        localhost/database_host:                        mysql-behat/g" /srv/pim/app/config/parameters_test.yml
    sed -i "s/localhost: 9200/elastic:changeme@elasticsearch:9200/g" /srv/pim/app/config/parameters_test.yml
    sed -i "s/product_index_name:                    akeneo_pim_product/product_index_name:                    behat_akeneo_pim_product/g" /srv/pim/app/config/parameters_test.yml
    sed -i "s/product_model_index_name:              akeneo_pim_product_model/product_model_index_name:              behat_akeneo_pim_product_model/g" /srv/pim/app/config/parameters_test.yml
    sed -i "s/product_and_product_model_index_name:  akeneo_pim_product_and_product_model/product_and_product_model_index_name:  behat_akeneo_pim_product_and_product_model/g" /srv/pim/app/config/parameters_test.yml
    sed -i "s/record_index_name:                     akeneo_referenceentity_record/record_index_name:                     behat_akeneo_referenceentity_record/g" /srv/pim/app/config/parameters_test.yml
    sed -i "s/product_proposal_index_name:           akeneo_pim_product_proposal/product_proposal_index_name:           behat_akeneo_pim_product_proposal/g" /srv/pim/app/config/parameters_test.yml
fi

