DEV_CATALOG_DIR=vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev
PROD_CATALOG_DIR=vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal

include vendor/akeneo/pim-community-dev/make-file/*.mk
