<?php


namespace Akeneo\AssetManager\Integration\PublicApi\Analytics;

use Akeneo\AssetManager\Infrastructure\PublicApi\Analytics\AggregatedAverageMaxNumberOfValuePerAsset;
use Akeneo\AssetManager\Integration\SqlIntegrationTestCase;
use PHPUnit\Framework\Assert;

/**
 * @copyright 2021 Akeneo SAS (http://www.akeneo.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
class AggregatedAverageMaxNumberOfValuePerAssetTest extends SqlIntegrationTestCase
{
    private AggregatedAverageMaxNumberOfValuePerAsset $aggregatedAverageMaxNumberOfValuePerAsset;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->aggregatedAverageMaxNumberOfValuePerAsset = $this->get('akeneo.asset_manager.infrastructure.public_api.analytics.aggregated_average_max_number_of_value_per_asset');

        $this->get('akeneoasset_manager.tests.helper.database_helper')->resetDatabase();
        $this->get('pim_volume_monitoring.volume.aggregation')->aggregate();
    }

    private function resetDB(): void
    {
        $this->get('akeneoasset_manager.tests.helper.database_helper')->resetDatabase();
    }

    /**
     * @test
     */
    public function it_returns_the_average_max_number_of_value_per_asset()
    {
        $averageMaxVolume = $this->aggregatedAverageMaxNumberOfValuePerAsset->fetch();
        Assert::assertEquals(0, $averageMaxVolume->getAverageVolume());
        Assert::assertEquals(0, $averageMaxVolume->getMaxVolume());
        Assert::assertEquals('average_max_number_of_values_per_asset', $averageMaxVolume->getVolumeName());
    }
}
