import React from 'react';
import {
    ActivityIcon,
    AddAttributeIcon,
    AkeneoIcon,
    ArrowDownIcon,
    ArrowIcon,
    ArrowLeftIcon,
    ArrowRightIcon,
    ArrowUpIcon,
    AssetCollectionIcon,
    AssetsIcon,
    AssociateIcon,
    AttributeBooleanIcon,
    AttributeFileIcon,
    AttributeLinkIcon,
    AttributeMultiSelectIcon,
    AttributeNumberIcon,
    AttributePriceIcon,
    AttributeSelectIcon,
    AttributeTextareaIcon,
    AttributeTextIcon,
    BarChartsIcon,
    BookIcon,
    BoxIcon,
    BrokenLinkIcon,
    CaddyAddIcon,
    CaddyCheckoutIcon,
    CaddyIcon,
    CardIcon,
    CategoryIcon,
    CheckIcon,
    CheckPartialIcon,
    CheckRoundIcon,
    ClockIcon,
    CloseIcon,
    CodeIcon,
    ColumnIcon,
    CompareIcon,
    ComponentIcon,
    CopyIcon,
    CreditsIcon,
    DangerIcon,
    DangerPlainIcon,
    DateIcon,
    DeleteIcon,
    DialogIcon,
    DownloadIcon,
    DragDropIcon,
    EditIcon,
    EntityIcon,
    EntityMultiIcon,
    EraseIcon,
    ExpandIcon,
    ExplanationPointIcon,
    FactoryIcon,
    FileCsvIcon,
    FileIcon,
    FileXlsxIcon,
    FiltersIcon,
    FolderIcon,
    FolderInIcon,
    FolderMovedIcon,
    FolderOutIcon,
    FolderPlainIcon,
    FoldersIcon,
    FoldersPlainIcon,
    FullscreenIcon,
    GiftIcon,
    GroupsIcon,
    HelpIcon,
    IconProps,
    IdIcon,
    InfoIcon,
    InfoRoundIcon,
    KeyboardIcon,
    KeyIcon,
    LightIcon,
    LinkIcon,
    ListIcon,
    LoaderIcon,
    LocaleIcon,
    LockIcon,
    MailIcon,
    MediaLinkIcon,
    MegaphoneIcon,
    MetricIcon,
    MinifyIcon,
    MoreIcon,
    MoreVerticalIcon,
    NotificationIcon,
    PanelCloseIcon,
    PanelOpenIcon,
    PlayIcon,
    PlusIcon,
    ProductIcon,
    ProductModelIcon,
    PublishIcon,
    RefreshIcon,
    RowIcon,
    SearchIcon,
    SectionIcon,
    SettingsIcon,
    ShopIcon,
    SupplierIcon,
    SystemIcon,
    TagIcon,
    UnpublishIcon,
    UnviewIcon,
    UploadIcon,
    ValueIcon,
    ViewIcon,
    WaveIcon,
} from '../icons';

type IconCollection = {
    [name: string]: React.ComponentType<IconProps>;
};

const icons: IconCollection = {
    Activity: ActivityIcon,
    AddAttribute: AddAttributeIcon,
    Akeneo: AkeneoIcon,
    ArrowDown: ArrowDownIcon,
    Arrow: ArrowIcon,
    ArrowLeft: ArrowLeftIcon,
    ArrowRight: ArrowRightIcon,
    ArrowUp: ArrowUpIcon,
    AssetCollection: AssetCollectionIcon,
    Assets: AssetsIcon,
    Associate: AssociateIcon,
    AttributeBoolean: AttributeBooleanIcon,
    AttributeFile: AttributeFileIcon,
    AttributeLink: AttributeLinkIcon,
    AttributeMultiSelect: AttributeMultiSelectIcon,
    AttributeNumber: AttributeNumberIcon,
    AttributePrice: AttributePriceIcon,
    AttributeSelect: AttributeSelectIcon,
    AttributeTextarea: AttributeTextareaIcon,
    AttributeText: AttributeTextIcon,
    BarCharts: BarChartsIcon,
    Book: BookIcon,
    Box: BoxIcon,
    BrokenLink: BrokenLinkIcon,
    CaddyAdd: CaddyAddIcon,
    CaddyCheckout: CaddyCheckoutIcon,
    Caddy: CaddyIcon,
    Card: CardIcon,
    Category: CategoryIcon,
    Check: CheckIcon,
    CheckPartial: CheckPartialIcon,
    CheckRound: CheckRoundIcon,
    Clock: ClockIcon,
    Close: CloseIcon,
    Code: CodeIcon,
    Column: ColumnIcon,
    Compare: CompareIcon,
    Component: ComponentIcon,
    Copy: CopyIcon,
    Credits: CreditsIcon,
    Danger: DangerIcon,
    DangerPlain: DangerPlainIcon,
    Date: DateIcon,
    Delete: DeleteIcon,
    Dialog: DialogIcon,
    Download: DownloadIcon,
    DragDrop: DragDropIcon,
    Edit: EditIcon,
    Entity: EntityIcon,
    EntityMulti: EntityMultiIcon,
    Erase: EraseIcon,
    Expand: ExpandIcon,
    ExplanationPoint: ExplanationPointIcon,
    Factory: FactoryIcon,
    FileCsv: FileCsvIcon,
    File: FileIcon,
    FileXlsx: FileXlsxIcon,
    Filters: FiltersIcon,
    Folder: FolderIcon,
    FolderIn: FolderInIcon,
    FolderMoved: FolderMovedIcon,
    FolderOut: FolderOutIcon,
    FolderPlain: FolderPlainIcon,
    Folders: FoldersIcon,
    FoldersPlain: FoldersPlainIcon,
    Fullscreen: FullscreenIcon,
    Gift: GiftIcon,
    Groups: GroupsIcon,
    Help: HelpIcon,
    Id: IdIcon,
    Info: InfoIcon,
    InfoRound: InfoRoundIcon,
    Keyboard: KeyboardIcon,
    Key: KeyIcon,
    Light: LightIcon,
    Link: LinkIcon,
    List: ListIcon,
    Loader: LoaderIcon,
    Locale: LocaleIcon,
    Lock: LockIcon,
    Mail: MailIcon,
    MediaLink: MediaLinkIcon,
    Megaphone: MegaphoneIcon,
    Metric: MetricIcon,
    Minify: MinifyIcon,
    More: MoreIcon,
    MoreVertical: MoreVerticalIcon,
    Notification: NotificationIcon,
    PanelClose: PanelCloseIcon,
    PanelOpen: PanelOpenIcon,
    Play: PlayIcon,
    Plus: PlusIcon,
    Product: ProductIcon,
    ProductModel: ProductModelIcon,
    Publish: PublishIcon,
    Refresh: RefreshIcon,
    Row: RowIcon,
    Search: SearchIcon,
    Section: SectionIcon,
    Settings: SettingsIcon,
    Shop: ShopIcon,
    Supplier: SupplierIcon,
    System: SystemIcon,
    Tag: TagIcon,
    Unpublish: UnpublishIcon,
    Unview: UnviewIcon,
    Upload: UploadIcon,
    Value: ValueIcon,
    View: ViewIcon,
    Wave: WaveIcon,
};

const getIcon = (name: string): React.ComponentType<IconProps> | undefined => icons[name];

export {getIcon};
