import {DATA_QUALITY_INSIGHTS_TAB_NAME, PRODUCT_ATTRIBUTES_TAB_NAME, PRODUCT_MODEL_ATTRIBUTES_TAB_NAME} from './ProductEditForm';
import {HTML_BREAKING_LINE_ELEMENTS_LIST, HTML_BLOCK_LEVEL_ELEMENTS_LIST} from './DOMElement';

export {
  HTML_BREAKING_LINE_ELEMENTS_LIST, HTML_BLOCK_LEVEL_ELEMENTS_LIST,
  DATA_QUALITY_INSIGHTS_TAB_NAME, PRODUCT_ATTRIBUTES_TAB_NAME, PRODUCT_MODEL_ATTRIBUTES_TAB_NAME,
}
