import {
  PRODUCT_ATTRIBUTES_TAB_NAME,
  PRODUCT_DATA_QUALITY_INSIGHTS_TAB_NAME,
  PRODUCT_MODEL_ATTRIBUTES_TAB_NAME,
  PRODUCT_MODEL_DATA_QUALITY_INSIGHTS_TAB_NAME
} from './ProductEditForm';
import {HTML_BLOCK_LEVEL_ELEMENTS_LIST, HTML_BREAKING_LINE_ELEMENTS_LIST} from './DOMElement';

export {
  HTML_BREAKING_LINE_ELEMENTS_LIST, HTML_BLOCK_LEVEL_ELEMENTS_LIST,
  PRODUCT_DATA_QUALITY_INSIGHTS_TAB_NAME, PRODUCT_MODEL_DATA_QUALITY_INSIGHTS_TAB_NAME,
  PRODUCT_ATTRIBUTES_TAB_NAME, PRODUCT_MODEL_ATTRIBUTES_TAB_NAME,
}

export const SUB_PRODUCT_MODEL_LEVEL = 1;
export const ROOT_PRODUCT_MODEL_LEVEL = 0;
export const MAX_VARIATION_LEVELS = 3;
