import DataQualityInsightsTabContent, {
  CONTAINER_ELEMENT_ID as DATA_QUALITY_INSIGHTS_TAB_CONTENT_CONTAINER_ELEMENT_ID,
} from './DataQualityInsightsTabContent';
import {ATTRIBUTES_TAB_CONTENT_CONTAINER_ELEMENT_ID} from '../../../constant';

export {
  DataQualityInsightsTabContent,
  DATA_QUALITY_INSIGHTS_TAB_CONTENT_CONTAINER_ELEMENT_ID,
  ATTRIBUTES_TAB_CONTENT_CONTAINER_ELEMENT_ID,
};
