bucket_location           = "EU"
firestore_project_id      = "akecld-prd-pim-fire-eur-fsan"
region                    = "europe-west1"
region_prefix             = "fsan-euw1"
portal_tenant_continent   = "europe-west1"
cloud_scheduler_time_zone = "Europe/Paris"
